<?php

class PostTableSeeder extends Seeder
{
	public function run()
	{
		$post1 = new Post();
		$post1->title = 'The Curious Incident of the Dog in the Night-Time';
		$post1->body = 'NYT Review (Ben Brantley): Ever had one of those days in the city when you feel like you forgot to put your skin on? Sure you have. It happens when you haven’t slept, or you drank too much the night before, or you’ve been brooding over bad news.
		All your senses, it seems, have been heightened to a painful acuity; your nerve endings are standing on guard. And every one of the manifold sights and sounds of urban life registers as a personal assault. You’re a walking target in a war zone, and that subway ride that awaits you looms like a descent into hell.
		Such a state of being is conjured with dazzling effectiveness in “The Curious Incident of the Dog in the Night-Time,” which opened on Sunday night at the Ethel Barrymore Theater. Adapted by Simon Stephens from Mark Haddon’s best-selling 2003 novel about an autistic boy’s coming-of-age, this is one of the most fully immersive works ever to wallop Broadway.
		So be prepared to have all your emotional and sensory buttons pushed, including a few you may have not known existed. As directed by Marianne Elliott (a Tony winner for the genius tear-jerker “War Horse”), with a production that retunes the way you see and hear, “Curious Incident” can be shamelessly manipulative.
		But more than any mainstream theater production I know, it forces you to adopt, wholesale, the point of view of someone with whom you may initially feel you have little in common. That’s Christopher Boone, a 15-year-old mathematical genius for whom walking down the street or holding a conversation is a herculean challenge.
		Played by the recent Juilliard school graduate Alex Sharp, in the kind of smashing Broadway debut young actors classically dream about, Christopher is in some ways a parent’s nightmare. He hates being touched, is bewildered by the common clichés of small talk and is sent into cataclysmic tantrums by any violation of his rigidly ritualized world.
		But he has a distinct advantage over most of us, and he knows it. “I see everything,” he says, while looking out the window during the first train ride of his life. “Most other people are lazy.
		 “They never look at everything,” he continues. “They do what is called glancing, which is the same word for bumping off something and carrying on in almost the same direction.” The pulsating show that surrounds him insists that we feel as fully as possible both the privilege and the penalty of seeing everything.
		Mr. Haddon’s novel is written in the first person, and translating a subjective point of view into external reality is always tricky. As we follow Christopher’s attempts to solve a local mystery — the murder of the dog next door — Mr. Stephens employs an assortment of narrative devices to keep us within his mind.
		Most prominent among these is the use of a special-education teacher, Siobhan (Francesca Faridany), as an intermediary between Christopher, her student, and the audience. In the first act, she reads to us from Christopher’s diarylike account, which he has evidently written at her request.
		At the beginning of the second act, she makes it clear that she has persuaded Christopher to turn his story into a play. This inevitably leads to a slightly cloying and hoary theatrical self-consciousness, with Christopher bossing around the performers of his mini-memoir.
		Yet the use of Siobhan as a tutelary stage manager bothered me less than it did when I saw “Curious Incident” in London (where it opened in 2012 and is still running, after picking up a slew of Olivier Awards). This is partly because the angular Ms. Faridany brings a welcome sharpness to the part.
		But it is also because Mr. Sharp’s Christopher, unlike Luke Treadaway’s equally good but more shiveringly vulnerable version in London, seems to own the play so completely. Everyone, even the helpful and intrusive Siobhan, registers as a product of his imagination.
		The people around him, embodied by a winning ensemble of everyday chameleons (including the first-rate Ian Barford and Enid Graham as Christopher’s parents), are his personal reconceptions of their real-life prototypes. We all employ a similar translation process in dealing with others, whether we acknowledge it or not. 
		And like Christopher, we are all continually trying to impose internal symmetry on the bewildering world outside. The great achievement of “Curious Incident” lies in how it turns the stage into the ordering mechanism of Christopher’s mind.
		The splendid design team — which includes Bunny Christie (set and costumes), Paule Constable (lighting), Finn Ross (video) and Ian Dickinson (sound) — gives us that mind as a sort of mathematical variation on the basic black box theater, with the walls of the set lined like graph paper. As Christopher navigates his way through an increasingly unfamiliar landscape, both physical and emotional, the arcs of his adventures are drawn into being.
		So are the shards of sensory overload. Life is messy in ways that graphs cannot accommodate. And when chaos comes, “Curious Incident” renders it in harrowing, meticulously detailed tours de force, whether the setting is a London subway or the room at home in which Christopher uncovers a cache of letters he didn’t know existed.
		It’s not all sound and light, though, that allow us entry into Christopher’s perspective. The choreographers Scott Graham and Steven Hoggett turn the cast members into a heaving sea of humanity that thwarts and threatens to consume Christopher.
		The realization of more individual interactions, especially between the touch-allergic young man and his parents, is often heartbreaking. These clumsy, hopeful moments become metaphors (to use a term Christopher loathes) for the pure, aching effort of making a connection with anybody else.
		Since the play is a detective story (its title comes from a Sherlock Holmes tale), I won’t say much more about its central mysteries. (There are more than one.) As is the way of shadowy conundrums, they tend to shrink when exposed to the light.
		Yet while this is brazenly a feel-good show (I’m sorry to tell you that a winsome puppy figures in its denouement), it wisely allows room for a lingering darkness. “It’s going to be all right,” grown-ups keep telling Christopher in bruised, self-betraying voices.
		No, it’s not. And on some level, Christopher will always know this, more piercingly that we can usually afford to acknowledge. That doesn’t stop him, or us, from basking in the triumphant glow of making it through the eternal obstacle course that is his — and our — daily life.';         
		$post1->user_id = User::first()->id;         
		$post1->save();

		$post2 = new Post();
		$post2->title = 'She Loves Me';
		$post2->body = 'NYT Review (Ben Brantley): Sometimes vanilla ice cream can taste like sweet deliverance. Such is the discovery made by one Amalia Balash in the 1963 musical “She Loves Me” — which has been rapturously revived in a new production by the Roundabout Theater Company — when she receives a gift of this frozen confection from an unlikely suitor.
		As Amalia trills her delight in a song that flies toward heaven on ascending high notes, audiences for Scott Ellis’s production, which opened on Thursday night at Studio 54, are likely to know exactly how she feels. That’s partly because “Vanilla Ice Cream” (for that is the number’s title, of course) is performed by Laura Benanti, an actress whose joyful soprano is a conduit for instant empathy.
		But it’s also because, from the moment the show begins, with a salutation to the working day by the employees of a perfume shop in 1930s Budapest, “She Loves Me” is a sustained reminder of the pleasures of exalted ordinariness. Written by Joe Masteroff (book), Jerry Bock (music) and Sheldon Harnick (lyrics), this tasty tale of love lost and found at the workplace is the great vanilla ice cream musical.
		Let me hasten to add that the ice cream I’m talking about isn’t the kind that comes in frost-rimed cartons in chain stores, but the hand-cranked, homemade variety that at its best is a transcendent marriage of human labor and carefully mixed ingredients. “She Loves Me” — which managed a modest 301 performances in its first Broadway incarnation and was eclipsed at the Tony Awards by the flash of “Hello, Dolly!” — is old-fashioned and unpretentious.
		But when embodied by a cast as expertly attuned as this one, which also includes a winning Zachary Levi and a scrumptious Jane Krakowski, it has a lingering and deeply satisfying sweetness usually lacking in brassier shows. It is also remarkably free of the shadows and subtexts that contemporary directors, like John Doyle and Bartlett Sher, keep uncovering in their reconceptions of vintage musicals. The cheerful seamlessness of “She Loves Me” defies deconstruction.
		That doesn’t mean the show — based on a play by Miklos Laszlo that inspired the enchanting 1940 Ernst Lubitsch film “The Shop Around the Corner” — is simple, though you may have that impression while you’re watching it. It succeeds in making you feel personally engaged by every one of its seven principal characters, who all work at the parfumerie owned by Mr. Maraczek (Byron Jennings), while convincing you that the most natural way to get to know people is through the medium of song.
		For “She Loves Me” only occasionally stops to deliver a big, self-contained production number. Instead, song runs through it like an underground stream (somewhere in middle Europe) that keeps bubbling to the surface. It sets the rhythms of salesmanship for Mr. Maraczek’s staff, from the courtly opening pitch to the farewell sung in impeccable harmony to each departing customer: “Thank you, madam, please call again. Do call again, madam.”
		Harmony is not all-pervasive. This is a place of business, after all, inhabited by an assortment of personalities that inevitably clash. For mysterious reasons, Mr. Maraczek has begun carping nastily at his trusted second-in-command, Georg Nowack (Mr. Levi), who in turn cannot seem to get along with Amalia, the shop’s newest employee.
		Mr. Levi (the star of television’s “Chuck”) and Ms. Benanti (who won a Tony in the title role of “Gypsy”) give good friction. Both their characters are convincingly willful, ambitious and, as it happens, romantic in a literary way. It makes perfect sense when we learn (before they do) that they have been corresponding with each other anonymously, under the rubric “Dear Friend,” through a lonely-hearts society.
		Most important to the tone of the show — and I mean this as a compliment — they both register as the sort of common-run urbanites you wouldn’t look at twice in the street. Each is the apotheosis of the average — as James Stewart and Margaret Sullavan were in the Lubitsch film (and as Tom Hanks and Meg Ryan were in Nora Ephron’s updated 1998 movie variation, “You’ve Got Mail”).
		By extension, the music within them that erupts to such disarming effect is the manifestation of irrepressible emotions that we all experience. At their most ecstatic, they take the form of two bravura solos, Amalia’s “Vanilla Ice Cream” and the title song, performed by Mr. Levi with a spontaneous, incredulous triumph that makes it all his own.
		But every one of the principals is allowed at least one similar moment, in a number that is as specifically expressive as handwriting. Each performer delivers with a flourish. That includes Michael McGrath, as a clerk who survives by keeping his head down, and Nicholas Barasch, as a delivery boy with dreams of success.
		Then there’s Ms. Krakowski, a Tony winner for “Nine,” who represses her glamorous diva side — so deliciously in evidence on the small screen in “30 Rock” and “Unbreakable Kimmy Schmidt” — to portray, with piquant charm, the love-singed Ilona Ritter, who’s been having an affair with the caddish Steven Kodaly, played by a vulpine Gavin Creel.
		He preens, she melts, and when they make music together, they rumba like the stars of a Copacabana floor show. Warren Carlyle did the character-rich choreography, which generously allows a clumsy waiter (Michael Fatica) to lead a virtuoso tango with his clientele.
		The restaurant here is ruled by Peter Bartlett, mugging tirelessly as an aggrieved maître d’. And like all of David Rockwell’s sets for the show, starting with the outsize Fabergé egg that is Maraczek’s Parfumerie, it’s a sumptuous eyeful. Mr. Ellis has successfully directed “She Loves Me” twice before, in the much-loved 1993 Broadway revival (also for Roundabout) and in London the next year, and he has once again assembled a deluxe design team to coax this shy show into full bloom.
		Jeff Mahshie’s costumes, Donald Holder’s lighting, Paul Gemignani’s musical direction — these elements combine to create an enhanced, shining reality that finds the daydream in daily existence. Far more than other workplace musicals of the period (“Pajama Game,” “How to Succeed in Business Without Really Trying”), “She Loves Me” offers the Platonic ideal of the 9-to-5 existence.
		It’s a world where even office antagonisms and anxiety can find an up-tempo synchronicity. And for those moments when you sense a song in your heart, there’s a first-class orchestra conveniently nearby to help you express yourself in a style that lives up to your bliss.';
		$post2->user_id = User::first()->id;
		$post2->save();

		$post3 = new Post();
		$post3->title = 'The Woodsman';
		$post3->body = 'NYT Review (Laura Collins-Hughes): The moment you step through the door, enchantment envelops you. Flocks of Mason jars hang suspended, glowing with amber light. Bare branches sprout from walls in the orchestra or reach scraggy arms across the ceiling, almost into the balcony. Thunder rumbles under birdsong.
		This magical environment is the world of James Ortiz’s “The Woodsman,” which uses puppets and actors, chorus and a lone violin (played by Naomi Florin) to reimagine the corner of L. Frank Baum’s Oz where the Tin Man came to be. This is what happened before he rusted, before that perky girl from Kansas fell from the sky.
		This largely wordless play with music (the score is by Edward W. Hardy) has run twice in the past two years at 59E59 Theaters, and has filled out a bit in its latest incarnation at New World Stages. Directed by Mr. Ortiz and Claire Karpen, it makes a little more room for laughter and isn’t in such a mad rush to tell its tale.
		This is a more assured production than the one I saw a year ago, and the encompassing visual lushness of its environment is new. But a fundamental stumble — more on that in a bit — still keeps it from fully blossoming to life.
		With a puppet witch who swoops through the sky, it’s a show that might be scary for small children. In her darkened home (lighting is by Catherine Clark and Jamie Roderick), the witch terrorizes her prisoner, Nimmee (Eliza Martin Simpson), a barefoot figure of Cinderella drudgery. The witch’s henchmen, a pack of puppet crows, could give flying monkeys a run for their money.
		But at the center of the story is Nick Chopper (Mr. Ortiz, who also designed the set and puppets), a woodsman who will become the Tin Man — or, as the script calls him, the Tin Woodsman — through a spell the witch casts on his ax. Before that, in easily the sweetest part of the show, he meets Nimmee and falls in love with her. Ms. Simpson does some charming clowning, and Mr. Ortiz frightens away a magnificent beast — a huge puppet that is part tiger, part bear and deserves more than a cameo — like a hiker encountering a black bear on the trail.
		One of the most breathtaking moments is astonishingly simple, as the lovers warm themselves in front of a fire. We see a light. We hear the crackling, popping sound of burning wood: a percussive illusion made of the chorus’s soft snapping and clapping. The rest is imagination.
		Mechanics get in the way of fantasy, though, at a crucial point, from the enchantment of the ax through Nick’s transformation into the Tin Woodsman. Just when we want the play to move us, there’s a frantic muddle instead. That long sequence contains the key to the story’s heart, and this abundantly beautiful show still needs to find it.';
		$post3->user_id = User::first()->id;
		$post3->save();

		$post4 = new Post();
		$post4->title = 'Avenue Q';
		$post4->body = "NYT Review (Ben Brantley): In the savvy, sassy and eminently likable 'Avenue Q,' which opened last night at the Golden Theater, an idealistic young man stares into the audience and sings, in a voice shiny with hope, 'Something's coming, something good.'
		Feeling some nagging tug of déjà vu? It's entirely possible. Some 40 years ago, another idealistic young man on another Broadway stage sang exactly the same lyrics, and has continued to do so in innumerable revivals ever since.
		But that was Tony, the starry-eyed hero of the breakthrough musical 'West Side Story.' And Tony is not to be confused with Princeton, the starry-eyed hero of 'Avenue Q,' which is a breakthrough musical of a very different stripe. After fervently anticipating the good things of the future, Tony went on to fall deeply and unconditionally in love, kill his girlfriend's brother and die violently, leaving an exceedingly pretty corpse, all within a matter of days.
		Princeton, too, has stars in his eyes. But after he sings about 'something coming,' he falls kind of, sort of in love (or maybe not); gets lost looking for his purpose in life; lies around moping in his apartment while takeout food cartons pile up; and when last heard from, is still very much alive, though in a continuing state of what looks like terminal uncertainty. And, oh, did I mention? He has two heads. That's literally. Figuratively, he has a lot more.
		Ah, what a difference half a century makes when it comes to leading men in American musicals. Tony, originally played by Larry Kert, belonged to an era in theater when sung emotions were big, clean and uncompromising. If you felt pretty, then Miss America could just resign; if you loved somebody, then the whole planet earth turned into a star.
		In 'Avenue Q,' first staged last spring Off Broadway at the Vineyard Theater, Princeton is embodied by both an oversize hand puppet and John Tartaglia, the always visible actor who manipulates Princeton and provides his voice. And he is very clearly part of a generation whose members find question marks creeping into every sentence they utter.
		Unlike the self-destructive, street-smart adolescents in 'West Side Story,' who always seemed about to explode whenever they sang or danced, the overschooled college graduates (some furry, some fleshy) of 'Avenue Q' look as if they might deflate as they work their way through bouncy ditties about failure, sex and the general pettiness of life.
		The role models for Princeton and his sometime girlfriend, Kate Monster (Stephanie D'Abruzzo), and their underemployed chums are not the misunderstood rebels portrayed by James Dean and Marlon Brando, but the gentle, instructive and fallible cloth creatures of 'Sesame Street.'
		This does not mean that the denizens of Avenue Q, an imaginary outpost of disenfranchised young New Yorkers, don't have the verve to rule a Broadway stage. Their creators, the songwriting team of Robert Lopez and Jeff Marx, demonstrate that ambivalence, indecision and low expectations can be the basis for a thoroughly infectious musical.
		If the plot line sometimes seems to sag and wander in the manner of its aimless characters (and its lopsided first act does go on too long), the individual performances and songs are never less than sharply focused and completely committed to the moment.
		Even more than 'Rent,' the only other show on Broadway pitched directly to theatergoers over 12 and under 40, 'Avenue Q' shimmeringly reflects the sensibility of that demographic segment so coveted by television advertisers. For Broadway producers, who count every head in their audiences that isn't gray as a bonus, 'Avenue Q' qualifies as a serious blessing.
		Like the more abrasive and ambitious 'Jerry Springer: The Opera,' currently onstage in London, 'Avenue Q' dares to co-opt television, the theater's longtime adversary. This show, which has a book by Jeff Whitty and is directed by Jason Moore, addresses Americans who were weaned on the small screen, and specifically on the educational antics of friendly anthropomorphic teachers like Big Bird and Cookie Monster.
		Mr. Lopez and Mr. Marx know that the songs you hear as a child are unlikely to leave your head entirely, and that whether you like it or not, such tunes and rhymes are likely to keep popping up as frames of reference for situations that on the surface could hardly seem less appropriate.
		That's the delicious central conceit that infuses every element of 'Avenue Q,' from its bright but gritty 'Sesame' streetscape of a set (designed by Anna Louizos, and deftly scaled up for Broadway) to its archly educational animated segments, which parse words and phrases like 'commitment' and 'one-night stand on video screens on either side of the stage.
		But it is in its songs and performances that 'Avenue Q' plays most piquantly on the contrasts between the world according to children's television and the reality of adult life. The nature of the twinkly songs, unfailingly tuneful and disgustingly irresistible, can be deduced from their titles: 'Everyone's a Little Bit Racist,' 'Schadenfreude,' 'The Internet Is for Porn' and 'You Can Be as Loud as the Hell You Want (When You're Makin' Love).'
		To deliver such numbers with any distancing sarcasm would be fatal. And even when their heads are flipping back and forth rhythmically like windshield wipers, the cast members (many of whom have worked in children's television) do not patronize their own perkiness. Irony is a conditioned reflex for these characters, and it doesn't get in the way of their basic sincerity.
		Some of the performers have puppets, worn on their arms, for alter egos. (Designed by Rick Lyon, who is also an ensemble member, these sophisticated variations on the sock puppet look much as they did in their downtown incarnations, though I'm told some of their colors have been heightened for the big time.)
		Mr. Tartaglia speaks not only for the callow Princeton but also for the buttoned-down broker (and repressed homosexual) Rod, whose more easygoing puppet roommate, Nicky, is portrayed by Mr. Lyon, also the voice for the pornography-loving recluse named Trekkie Monster. Ms. D'Abruzzo's puppetry embraces both the wistful kindergarten teacher Kate and her rival, a bosomy singer named Lucy T. Slut.
		Mr. Lyon and Jennifer Barnhart help, er, flesh out the other puppet characters, who include Kate's crotchety employer, who has an unprintable name, and two blissfully obnoxious figures called the Bad Idea Bears, who resemble those hideous Care Bears and are given to tempting the other characters to do things like drink to excess, go home with strangers and consider suicide.
		There are also three puppet-free performers who admirably hold their own. Natalie Venetia Belcon plays the jocular superintendent of Princeton's building, who happens to be Gary Coleman, the former child television star, and the perfect emblem for a world in which everyone is, to some degree, a Peter Pan with a five o'clock shadow.
		The hearty Jordan Gelber is Brian, the would-be stand-up comedian whose idea of a routine is to sing 'I'm not wearing any underwear today' over and over. And Ann Harada is his fiancée, Christmas Eve, a Japanese therapist who has not quite mastered English.
		Like Princeton, Christmas Eve emerges as a vivid reminder of the difference between musicals past and present. Counseling the romantically troubled Kate, she temporarily drops her habitually pinched voice to deliver, in the show's wittiest coup de théâtre, a full-throated ballad in the manner of a 1950's musical diva.
		You may find this song brings to mind another piece of purely American Orientalia, 'Something Wonderful' from 'The King and I.' Of course Marx and Lopez see the world in terms slightly different from Rodgers and Hammerstein. 'The more you love someone/The more you want to kill him,' Christmas sings in a shivery, rafters-shaking alto. And though you can construe the song as a satire if you choose, there is no doubt that Christmas means every word she sings.";
		$post4->user_id = User::first()->id;
		$post4->save();

		$post5 = new Post();
		$post5->title = 'Waitress';
		$post5->body = 'Variety Review (Frank Rizzo): Based on writer-director Adrienne Shelley’s 2007 indie film, Jessie Nelson’s book follows the movie’s narrative, beginning just as Jenna, in the midst of planning to leave her abusive husband, Earl (Joe Tippett), discovers she is pregnant. She decides to have the baby — but clearly it’s not a child she wants.
		She finds support from her fellow waitresses, not dissimilar to the characters in the diner film “Alice Doesn’t Live Here Anymore” and its sitcom spinoff, “Alice.” There’s mousy, nervous Dawn (Jeanna De Waal) and tough, wisecracking Becky (Keala Settle). There’s also brusque Cal (Eric Anderson), the cook/manager, and the diner’s folksy-crusty owner, Joe (Dakin Matthews, in a performance as easygoing and tasty as molasses). 
		Things get more complicated when Jenna starts an affair with her newly-arrived-in-town — and married — gynecologist, Dr. Pomatter (Drew Gehling). As played by the sweetly awkward and disarmingly gentle Gehling, it’s the type of romance that, in another show, you would hope would work out somehow. But this distaff-centric tuner is not simply about getting Prince Charming, but also getting its heroine to clean up her own messes, take action and discover her maternal worth.
		A comic-romantic subplot with Dawn and an Internet date with Ogie (Jeremy Morse, in a firecracker of a performance) brightens the mood, with Morse having a pair of highly charged numbers: “Never Getting Rid of Me,” which nicely contrasts with Earl’s creepy possessiveness, and the silly but joyous “I Love You Like a Table.”
		Dawn and Becky have their musical moments, too, especially Settle’s searing “I Didn’t Plan It,” when Becky owns up to her own marital imperfections. (“Its not right/but it’s mine/and it’s finally something to feel.”) These flawed or broken characters live with their fates as best as they can, some better than others.  When Jenna asks Cal if he’s happy, he responds, “Happy enough.” Jenna wants more than enough.
		But making Earl so relentlessly horrible makes Jenna’s inability to leave him not just indecisive but something more worrisome. (In the film, Jeremy Sisto’s character is more wily and seductive in his pathology.) Meanwhile, there’s little evidence for the good doctor being Jenna’s lost soulmate, despite his loving bedside manner, and the 11th-hour cameo of Dr. Pomatter’s wife is a questionable choice, at least as it’s presented now.
		Mueller’s performance transcends the show’s imperfections. She’s funny, frisky and likable. She sings Bareilles’ songs beautifully, giving every word significance and interest even as the tunes in the second half slip increasingly into thicker sentiment.
		Leading the sisterhood of creatives, director Diane Paulus fills the production with clever touches — a scalloped pie-crust proscenium, a fluid and easygoing flow and a natural truthfulness in the performances. Scott Pask’s set design authentically evokes the chrome, neon and Naugahyde look of a down-home joint, as do Kenneth Posner’s lighting and Suttirat Larlarb’s seemingly off-the rack costumes. Another nice touch: The band is positioned onstage in a side room of the diner, further populating the place — and justifying the diner’s three waitresses.
		In a show that celebrates motherhood, pie and extramarital affairs, “Waitress” could be a kind of comfort-food musical. But at this point it still needs more filling.';
		$post5->user_id = User::first()->id;
		$post5->save();
	}
}

